#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument

#Check if the IP address of the argument is provided
if [ -z "$1" ];then
	echo "usage: $0 {IP_ADDRESS}"
	exit 1
fi
#Ping the specified IP address five times
ping -c 5 "$1"
