#!/usr/bin/env bash
#bash scipt that displays numbers 1 - 100 and :
#displays Fizz Buzz if the number is multiple of both 3 and 5
#diplays Fizz if the number is a multiple of 3
#displays Buzz if the number is multiple of 5

for number in {1..100}
do
	if [ $((number % 15)) -eq 0 ];then
		echo "Fizz Buzz"
	elif [ $((number % 3)) -eq 0 ];then
		echo "Fizz"
	elif [ $((number % 5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$number"
	fi
done
