#!/usr/bin/env bash

for ((num = 1; num <= 100; num++)); do
    output=""
    if ((num % 3 == 0)); then
        output+="Fizz"
    fi
    if ((num % 5 == 0)); then
        output+="Buzz"
    fi
    if [[ -z $output ]]; then
        output="$num"
    fi
    echo "$output"
done

