#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

repititions=10

counter=1

while [ $counter -le $repititions ]
do
	if [ $counter -eq 9 ];then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done	
