#!/usr/bin/env bash

# Loop through hours from 0 to 12
for (( hour = 0; hour <= 12; hour++ )); do
    echo "Hour: $hour"
    
    # Loop through minutes from 1 to 59
    for (( minute = 1; minute <= 59; minute++ )); do
        echo "$minute"
    done
done

